version: '3.8'
services:
  database:
    image: postgres
    ports:
      - "2222:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finantialdb
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: always
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
  mock_app:
    build:
      context: .
      dockerfile: Dockerfile.mock_app  # Specify the Dockerfile for your mock app
    depends_on:
      - database