version: '3.8'
services:

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: SrUVENGThsaleNC
      POSTGRES_PASSWORD: g9JYX9q*
      POSTGRES_DB: finantial_data
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080